QEMU_ARGS="-m 8G \
-smp 8,sockets=1,cores=8,threads=1 \
-cpu rv64 \
-machine virt \
-accel tcg,thread=multi \
-device virtio-scsi,id=scsi0,num_queues=4 \
-drive file=/path/to/vm.qcow2,format=qcow2,if=none,id=hd0,cache=writeback,discard=unmap,detect-zeroes=unmap \
-device scsi-hd,bus=scsi0.0,drive=hd0 \
-netdev bridge,br=virbr0,id=net0 \
-device virtio-net,netdev=net0,speed=10000,duplex=full,mac=00:05:06:07:08:09 \
-device qemu-xhci \
-device usb-kbd \
-device virtio-tablet \
-device virtio-sound \
-device virtio-gpu \
-display vnc=127.0.0.1:30 \
-serial telnet:127.0.0.1:2030,server,nowait \
-drive if=pflash,format=qcow2,readonly=on,file=/usr/share/edk2/riscv/RISCV_VIRT_CODE.qcow2 \
-drive if=pflash,format=qcow2,readonly=off,file=/path/to/RISCV_VIRT_VARS.qcow2"
