QEMU_ARCH="loongarch64"

QEMU_ARGS="-m 4G \
-smp 2,sockets=1,cores=2,threads=1 \
-cpu la464 \
-machine virt,firmware=/usr/share/edk2/loongarch64/QEMU_EFI.fd \
-accel tcg,thread=multi \
-device virtio-scsi,id=scsi0,num_queues=4 \
-drive file=/path/to/vm.qcow2,format=qcow2,if=none,id=hd0,cache=unsafe,discard=unmap,detect-zeroes=unmap \
-device scsi-hd,bus=scsi0.0,drive=hd0 \
-netdev bridge,br=virbr0,id=net0 \
-device virtio-net,netdev=net0,speed=10000,mac=00:aa:bb:bc:dd:ee \
-device qemu-xhci \
-device usb-kbd \
-device virtio-tablet \
-device virtio-gpu \
-display vnc=127.0.0.1:40 \
-serial telnet:127.0.0.1:2040,server,nowait"
