QEMU_ARGS="-m 4G \
-smp 2,sockets=1,cores=2,threads=1 \
-cpu cortex-a76 \
-machine virt \
-accel tcg,thread=multi \
-device virtio-scsi-pci,id=scsi0,num_queues=4 \
-drive file=/path/to/vm.qcow2,format=qcow2,if=none,id=hd0,cache=unsafe,discard=unmap,detect-zeroes=unmap \
-device scsi-hd,bus=scsi0.0,drive=hd0 \
-netdev bridge,br=virbr0,id=net0 \
-device virtio-net-pci,netdev=net0,speed=10000,mac=00:0a:0b:0c:0d:0e \
-device qemu-xhci \
-device usb-kbd \
-device virtio-tablet \
-device virtio-gpu \
-display vnc=127.0.0.1:20 \
-serial telnet:127.0.0.1:2020,server,nowait \
-bios /usr/share/edk2/aarch64/QEMU_EFI.fd"
