MACVTAP="macvtap0"
QEMU_ARCH="x86_64"
QEMU_ARGS="-m 4G \
-smp 4,sockets=1,cores=4,threads=1 \
-cpu host,kvm=off \
-machine type=q35,accel=kvm,usb=on,firmware=/usr/share/edk2/ovmf/OVMF_CODE.fd \
-device virtio-scsi,num_queues=4 \
-drive file=/path/to/vm.qcow2,format=qcow2,if=none,id=hd0,cache=unsafe,discard=unmap,detect-zeroes=unmap \
-device scsi-hd,drive=hd0 \
-netdev tap,fd=3,id=net0 \
-device virtio-net,netdev=net0,speed=10000,duplex=full,mac=00:01:02:03:04:05 \
-device virtio-tablet \
-device virtio-vga \
-display vnc=127.0.0.1:10 \
-serial telnet:127.0.0.1:2010,server,nowait"
